---
- hosts: 10.10.10.1
  connection: local
  gather_facts: no
  tasks:
    - name: Create/Delete tenant
      bcf_tenant:
          controller: '{{ inventory_hostname }}'
          name: auto_tenant1
          state: present
          validate_certs: false
          access_token: 'qwdQnLKh865FUMWsQGNYunuleNdT2nqH'

    - name: Create/Delete segment
      bcf_segment:
          controller: '{{ inventory_hostname }}'
          tenantName: auto_tenant1
          segmentName: auto_segment1
          tenantState: present
          segmentState: present
          validate_certs: false
          access_token: 'qwdQnLKh865FUMWsQGNYunuleNdT2nqH'

    - name: Create/Delete logical router
      bcf_logicalrouter:
          controller: '{{ inventory_hostname }}'
          tenantName: auto_tenant1
          segmentName: auto_segment1
          ipcidr: '2.2.2.2/24'
          segIntState: present
          validate_certs: false
          access_token: 'qwdQnLKh865FUMWsQGNYunuleNdT2nqH'

